version: '2.1'

services:
  rallytics:
    build:
      context: .
 #     dockerfile: Dockerfile.debug
    environment:
      - VIRTUAL_HOST=ws://rallytics-ws.localtest.me
      - VIRTUAL_PORT=8080
    command:
      - -h
      - redis
  nginx:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=rallytics.localtest.me
  nginx-proxy:
    image: mesudip/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: redis
#    ports:
      # - 6379:6379
